# Services for EV Charging Extractor

trigger_extraction:
  name: Trigger Manual Extraction
  description: Manually trigger processing of EV charging emails and EVCC data
  fields:
    email_search_days:
      name: Email Search Days
      description: Number of days back to search for emails (overrides config setting)
      required: false
      selector:
        number:
          min: 1
          max: 365
          step: 1
          mode: slider

debug_email_parsing:
  name: Debug Email Parsing
  description: Debug function to troubleshoot email parsing issues
  fields:
    email_search_days:
      name: Email Search Days
      description: Number of days back to search for debug emails
      required: false
      default: 7
      selector:
        number:
          min: 1
          max: 90
          step: 1
          mode: slider

debug_evcc_connection:
  name: Debug EVCC Connection
  description: Debug EVCC connection and data retrieval

export_to_csv:
  name: Export to CSV
  description: Export all charging data to CSV file

get_database_stats:
  name: Get Statistics
  description: Get database statistics and summary information

clear_and_reprocess:
  name: Clear Data and Reprocess
  description: Clear all existing data and reprocess emails from scratch
  fields:
    email_search_days:
      name: Email Search Days
      description: Number of days back to search for emails
      required: false
      default: 200
      selector:
        number:
          min: 1
          max: 365
          step: 1
          mode: slider